clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:

  push-to-ecr-on-push:
    image: plugins/ecr
    ecr_access_key: $${AWS_ACCESS_KEY_ID}
    ecr_secret_key: $${AWS_SECRET_ACCESS_KEY}
    repo: 724009402066.dkr.ecr.eu-west-1.amazonaws.com/habx-${DRONE_REPO_NAME}
    region: eu-west-1
    dockerfile: Dockerfile
    build_args_from_env:
      - NPM_TOKEN
    tags:
      - ${DRONE_COMMIT_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:7}
      - latest-${DRONE_COMMIT_BRANCH/\//-}
    secrets: [ aws_access_key_id, aws_secret_access_key, npm_token ]
    when:
      event: push
      branch: [dev, feature/*, release/*]

  push-to-ecr-on-tag:
    image: plugins/ecr
    ecr_access_key: $${AWS_ACCESS_KEY_ID}
    ecr_secret_key: $${AWS_SECRET_ACCESS_KEY}
    repo: 724009402066.dkr.ecr.eu-west-1.amazonaws.com/habx-${DRONE_REPO_NAME}
    region: eu-west-1
    dockerfile: Dockerfile
    tags:
      - ${DRONE_TAG}
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
      - npm_token
    when:
      event: tag

  duplicate-service:
    image: aelg/drone-service-duplicator
    kubernetes_server: https://api.paris.k8s.habx.fr
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - source: kubernetes_token_paris
        target: kubernetes_token
    environment:
      - SOURCE_NAMESPACE=dev
      - TARGET_NAMESPACE=${DRONE_COMMIT_BRANCH##feature/}
      - SERVICE_LABEL=${DRONE_REPO_NAME}
      - MATCH_ON_KEY=repo
      - HOST=${DRONE_COMMIT_BRANCH##feature/}.${DRONE_REPO_NAME}.habx-dev.fr
    when:
      branch: [ feature/* ]

  deploy-to-dev:
    image: aelg/drone-kubernetes
    kubernetes_server: https://api.paris.k8s.habx.fr
    kubernetes_token: ${KUBERNETES_TOKEN}
    namespace: ${DRONE_COMMIT_BRANCH##feature/}
    deployment: ${DRONE_REPO_NAME}
    container: ${DRONE_REPO_NAME}
    repo: 724009402066.dkr.ecr.eu-west-1.amazonaws.com/habx-${DRONE_REPO_NAME}
    tag: ${DRONE_COMMIT_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:7}
    secrets:
      - source: slack_incoming_webhook
        target: slack_incoming_webhook
      - source: kubernetes_token_paris
        target: kubernetes_token
    when:
      event: push
      branch: [dev, feature/*]

  deploy-to-release:
    image: aelg/drone-kubernetes
    kubernetes_server: https://api.paris.k8s.habx.fr
    kubernetes_token: ${KUBERNETES_TOKEN}
    namespace: release
    deployment: ${DRONE_REPO_NAME}
    container: ${DRONE_REPO_NAME}
    repo: 724009402066.dkr.ecr.eu-west-1.amazonaws.com/habx-${DRONE_REPO_NAME}
    tag: ${DRONE_COMMIT_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:7}
    secrets:
      - source: kubernetes_token_paris
        target: kubernetes_token
      - source: slack_incoming_webhook
        target: slack_incoming_webhook
    when:
      event: push
      branch: [release/*]

  deploy-to-staging-on-tag:
    image: aelg/drone-kubernetes
    kubernetes_server: https://api.paris.k8s.habx.fr
    kubernetes_token: ${KUBERNETES_TOKEN}
    namespace: staging
    deployment: ${DRONE_REPO_NAME}
    container: ${DRONE_REPO_NAME}
    repo: 724009402066.dkr.ecr.eu-west-1.amazonaws.com/habx-${DRONE_REPO_NAME}
    tag: ${DRONE_TAG}
    secrets:
      - source: kubernetes_token_paris
        target: kubernetes_token
      - source: slack_incoming_webhook
        target: slack_incoming_webhook
    when:
      event: tag
